- job:
    name: python-mistralclient-devstack-dsvm
    parent: legacy-dsvm-base
    run: playbooks/legacy/python-mistralclient-devstack-dsvm/run.yaml
    post-run: playbooks/legacy/python-mistralclient-devstack-dsvm/post.yaml
    timeout: 4200
    required-projects:
      - openstack-dev/devstack
      - openstack-infra/devstack-gate
      - openstack/heat
      - openstack/mistral
      - openstack/mistral-dashboard
      - openstack/python-mistralclient

- project:
    check:
      jobs:
        - python-mistralclient-devstack-dsvm
        # TripleO jobs that deploy Mistral.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario003-multinode-oooq will only
        # run on stable/pike while the -container will run in Queens
        # and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario003-multinode-oooq
        - tripleo-ci-centos-7-scenario003-multinode-oooq-container
    gate:
      jobs:
        - python-mistralclient-devstack-dsvm
        - tripleo-ci-centos-7-scenario003-multinode-oooq
        - tripleo-ci-centos-7-scenario003-multinode-oooq-container

