- job:
    name: python-mistralclient-functional-devstack
    parent: devstack-tox-functional-consumer
    timeout: 9000
    vars:
      devstack_plugins:
        mistral: https://git.openstack.org/openstack/mistral
        heat: https://git.openstack.org/openstack/heat
      devstack_services:
        heat: true
        h-api: true
        h-api-cfn: true
        h-api-cw: true
        h-eng: true
      tox_envlist: functional
      tox_environment:
        IDENTITY_API_VERSION: 3
        PYTHONUNBUFFERED: 'true'
        MISTRAL_USE_MOD_WSGI: true
        MISTRAL_RPC_IMPLEMENTATION: oslo
        MYSQL_ROOT_PW: secretdatabase
    required-projects:
      - openstack/heat
      - openstack/mistral
      - openstack/python-mistralclient

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - python-mistralclient-functional-devstack
        # TripleO jobs that deploy Mistral.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario003-multinode-oooq will only
        # run on stable/pike while the -container will run in Queens
        # and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario003-multinode-oooq
        - tripleo-ci-centos-7-scenario003-multinode-oooq-container
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - python-mistralclient-functional-devstack
        - tripleo-ci-centos-7-scenario003-multinode-oooq
        - tripleo-ci-centos-7-scenario003-multinode-oooq-container
        - openstack-tox-lower-constraints

