- job:
    name: python-mistralclient-functional-devstack
    parent: devstack-tox-functional-consumer
    timeout: 9000
    vars:
      devstack_plugins:
        mistral: https://opendev.org/openstack/mistral
        heat: https://opendev.org/openstack/heat
      devstack_services:
        heat: true
        h-api: true
        h-api-cfn: true
        h-api-cw: true
        h-eng: true
      tox_envlist: functional
      tox_environment:
        IDENTITY_API_VERSION: 3
        PYTHONUNBUFFERED: 'true'
        MISTRAL_USE_MOD_WSGI: true
        MISTRAL_RPC_IMPLEMENTATION: oslo
        MYSQL_ROOT_PW: secretdatabase
    required-projects:
      - openstack/heat
      - openstack/mistral
      - openstack/mistral-lib
      - openstack/mistral-extra
      - openstack/python-mistralclient

- project:
    templates:
      - check-requirements
      - openstack-python3-xena-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-cover:
            voting: false
            irrelevant-files:
              - ^.zuul.yaml$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - python-mistralclient-functional-devstack
    gate:
      jobs:
        - python-mistralclient-functional-devstack

